version: 2
jobs:
  build:
    docker:
      - image: liefproject/doc:sphinx_lief_theme_4
    environment:
      LIEF_VERSION: 0.14.0
      LIEF_INPUT: "/root/project/LIEF-0.14.0-Linux-x86_64/include/LIEF /root/project/LIEF-master/doc/doxygen"
      LIEF_EXCLUDE: "/root/project/LIEF-0.14.0-Linux-x86_64/include/LIEF/third-party"
      LIEF_INCLUDE_PATH: "/root/project/LIEF-0.14.0-Linux-x86_64/include"
      LIEF_DOXYGEN_XML: "/root/project/doxygen/xml"
      LIEF_DOXYGEN_WARN_FILE: "/tmp/doxygen-warn.log"
    working_directory: /root/project
    steps:
      - run: mkdir -p workspace
      - run:
          name: Boostrap LIEF SDK & Wheel
          command: |
            curl -LO https://raw.githubusercontent.com/lief-project/doc/main/.circleci/bootstrap_env.py
            python3 --version
            python3 ./bootstrap_env.py
            python3 -c "import lief;print(lief.__version__)"
      - run:
          name: Get LIEF Sources
          command: |
            curl -LO https://github.com/lief-project/LIEF/archive/master.tar.gz
            tar -xvf master.tar.gz
      - run:
          name: Generate doxygen documentation
          command: |
            doxygen LIEF-master/doc/doxygen/Doxyfile
      - run:
          name: Generate Sphinx documentation
          command: |
            cd LIEF-master/doc
            sphinx-build -a -E -j8 -w /tmp/sphinx-warn.log ./sphinx ./sphinx-doc
      - run:
          name: Copy doc tree
          command: |
            cp -r ${CIRCLE_WORKING_DIRECTORY}/LIEF-master/doc/sphinx-doc ${CIRCLE_WORKING_DIRECTORY}/workspace/doc
            cp -r ${CIRCLE_WORKING_DIRECTORY}/doxygen/html ${CIRCLE_WORKING_DIRECTORY}/workspace/doc/doxygen
      - persist_to_workspace:
          root: workspace
          paths:
            - .
      - store_artifacts:
          path: /tmp/sphinx-warn.log
          destination: sphinx-warnings

      - store_artifacts:
          path: /tmp/doxygen-warn.log
          destination: doxygen-warnings
  deploy:
    docker:
      - image: liefproject/doc-deploy:latest
    working_directory: /root/project
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: |
            python3 .github/main.py

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
